ALTER TABLE IncDecCell ADD COLUMN iconName TEXT
ALTER TABLE SliderCells ADD COLUMN iconName TEXT
ALTER TABLE StringCells ADD COLUMN iconName TEXT
ALTER TABLE SwitchCells ADD COLUMN iconName TEXT
ALTER TABLE VoiceCells ADD COLUMN iconName TEXT
ALTER TABLE ButtonCells ADD COLUMN iconName TEXT

